import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppProviders from "./providers";
import { Sidebar } from "@/components/layout/Sidebar";
import { Header } from "@/components/layout/Header";
import { Analytics } from '@vercel/analytics/react';
import { reportWebVitals } from '@/lib/vitals';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppProviders>
          <div className="flex">
            <Sidebar />
            <div className="flex-1 min-h-dvh flex flex-col">
              <a href="#main" className="skip-link">İçeriğe atla</a>
              <Header />
              <main id="main" className="flex-1">{children}<Analytics /></main>
            </div>
          </div>
        </AppProviders>
      </body>
    </html>
  );
}
